import { FloorplanAppState } from '../types';

export const planningMockState: FloorplanAppState = {
  mode: 'planning',
  floorplanImageUrl: '/floorplans/floorplan_1.png',
  imageScale: 1.0,
  imageRotation: 0,
  scaleRatio: 0.5,
  devices: [
    {
      id: 'placeholder-hub-1',
      type: 'hub',
      name: 'Hub',
      x: 300,
      y: 400,
      placeholder: true,
    },
    {
      id: 'placeholder-desk-1',
      type: 'desk_occupancy',
      name: 'Desk Occupancy',
      x: 500,
      y: 600,
      placeholder: true,
    },
  ],
  unassignedDevices: [],
  selectedElementId: null,
  currentTypeToPlace: null,
  currentUnassignedDeviceIdToPlace: null,
  isMeasuring: false,
  isCalibrating: false,
};

export const viewMockState: FloorplanAppState = {
  mode: 'view',
  floorplanImageUrl: '/floorplans/floorplan_1.png',
  imageScale: 1.0,
  imageRotation: 0,
  scaleRatio: 0.5,
  devices: [
    {
      id: 'device-1',
      type: 'hub',
      name: 'Hub',
      x: 300,
      y: 400,
      placeholder: false,
      assigned: true,
      uuid: 'HUB-0001',
      label: '300239',
      active: true,
      mountingHeight: 12,
      mountingLocation: 'INSIDE',
      battery: 92,
      capacity: 1,
      powerType: 'Battery',
    },
    {
      id: 'device-2',
      type: 'eec',
      name: 'Exit/Entry Counter',
      x: 500,
      y: 200,
      placeholder: false,
      assigned: true,
      uuid: 'EEC-0002',
      label: '300240',
      active: false,
      mountingHeight: 8,
      mountingLocation: 'OUTSIDE',
      battery: 55,
      capacity: 1,
      powerType: 'Battery',
    },
  ],
  unassignedDevices: [],
  selectedElementId: null,
  currentTypeToPlace: null,
  currentUnassignedDeviceIdToPlace: null,
  isMeasuring: false,
  isCalibrating: false,
};

export const editMockState: FloorplanAppState = {
  mode: 'edit',
  floorplanImageUrl: '/floorplans/floorplan_1.png',
  imageScale: 1.0,
  imageRotation: 0,
  scaleRatio: 0.5,
  devices: [
    {
      id: 'device-1',
      type: 'hub',
      name: 'Hub',
      x: 300,
      y: 400,
      placeholder: false,
      assigned: true,
      uuid: 'HUB-0001',
      label: '300239',
      active: true,
      mountingHeight: 12,
      mountingLocation: 'INSIDE',
      battery: 92,
      capacity: 1,
      powerType: 'Battery',
    },
  ],
  unassignedDevices: [
    {
      id: 'device-unassigned-1',
      type: 'iaq',
      name: 'IAQ Sensor',
      x: 0,
      y: 0,
      placeholder: false,
      assigned: false,
      uuid: 'IAQ-NEW-01',
      label: 'IAQ-Temp',
      active: false,
      mountingHeight: 0,
      mountingLocation: 'INSIDE',
      battery: 100,
      capacity: 1,
      powerType: 'Battery',
    },
  ],
  selectedElementId: null,
  currentTypeToPlace: null,
  currentUnassignedDeviceIdToPlace: null,
  isMeasuring: false,
  isCalibrating: false,
  editSnapshot: {
    devices: [],
    unassignedDevices: [],
  },
};
